os: linux
language: cpp
services: [docker]
sudo: true
compiler:
  - clang
  - gcc
before_script:
  - docker build . -f .travis/${CC}.docker -t casarest/${CC}
script:
  - docker run casarest/${CC} make test
